---
version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid # Cambia tu zona horaria si es el caso
    volumes:
      - ${CONFIG_DIR}:/config
      # - /path/to/data1:/data1
      # - /path/to/data2:/data2
    #ports:
    #  - 8384:8384
    #  - 22000:22000/tcp
    #  - 22000:22000/udp
    #  - 21027:21027/udp
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=updater"  # Utilizo esta label para que WatchTower actualice mis containers
    networks:
      - proxy-network
      - internal
networks:
  proxy-network:
    external: true
  internal: